###
GET http://localhost:3000/

###
GET http://localhost:3000/api/


###
GET http://localhost:3000/api/read-book/3

###
POST http://localhost:3000/api/add-book
Content-Type: application/json

{
  "name": "tossddfffhiba",
  "price": "22323",
  "description": "best of the best"
}

###
PUT  http://localhost:3000/api/update-book/7
Content-Type: application/json

{
  "name": "Zenbook 13 pro",
  "price": "2599",
  "description": "best of the best 2009"
}

###
DELETE http://localhost:3000/api/delete-book/1